/** SKAF */

#ifndef _HEAVY_CONTEXT_POLYCULE_HPP_
#define _HEAVY_CONTEXT_POLYCULE_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlCast.h"
#include "HvMath.h"
#include "HvControlBinop.h"
#include "HvSignalBiquad.h"
#include "HvControlVar.h"
#include "HvControlSystem.h"
#include "HvControlUnop.h"
#include "HvSignalVar.h"
#include "HvSignalLine.h"

class Heavy_polycule : public HeavyContext {

 public:
  Heavy_polycule(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_polycule();

  const char *getName() override { return "polycule"; }
  int getNumInputChannels() override { return 2; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        BASS = 0x18E7F0B7, // Bass
        CLIPPING = 0x300856D3, // Clipping
        DIODE_NEG = 0xB1C3A529, // Diode_neg
        DIODE_POS = 0xF4D0459, // Diode_pos
        GAIN = 0x677821DA, // Gain
        HUMP = 0xB2B2CA1D, // Hump
        LEVEL = 0x3D02EA21, // Level
        TONE = 0xE3C2D868, // Tone
        VOICE = 0xAC4A4490, // Voice
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cMsg_4x3oilWE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_TC9o2kz8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_IFqHHym8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZqSXEZAv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vL9a4nRD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_T44yElEo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ORs2JGqb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XS5iyhlb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_e1RMSDlE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_3DhoQbrM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TAbWBTBr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WW4KDjK2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sue5sZ8Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_34bo36jI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0RmdBP81_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rrz9kOvO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nHvJ9QlT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Rh37OuFq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ACtj0btH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_AHHHoaVa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GRVKrbjC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_lvZmeRxL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vUja36ow_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kWSKR1HY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xbU2Syu3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tYjdiNxk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WHFUgMF1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_1mWQw5eI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Eoz0PwbO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ebGIIkw4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JsYKaaJb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1iggz5hh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cegagA1a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pFAZIk2o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_B4ZO7Tbg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4dWyDkbH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_v0KGgi10_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Q5731c6P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_w6ekVKib_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_kcVxJgKE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oBBW4syz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k4udKMhm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rCVE6Mzx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_glj3pwTo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R2TVZSKV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cW5Lsfh9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wnYGApYe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Mexnbtin_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lyEExz6F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jLuFgeqI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VeSQbFES_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YE8MpmLJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CFDGpu1y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Xg39tw28_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AKNTLWx0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0MODuUKy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6aQfvPOz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F9UbFMyW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_x5SIAMJh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8HEdGADr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NT72Oczj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6sFgKLWy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rP6ZRrw8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OdmWq08A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nNPauLjB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RvXiE4wD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_g6UKIeBD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CEdjMHsG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3xdndUNh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KHBNQjpY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_EctSGFui_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_6cgipBeO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7H9YyhX8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FkiukWLl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8D2MSav8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xatg3L5l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gi2tqjb9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hw50gjbw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Q2j1jaeZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_08zFfQf0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4GQCVGZe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3qxZhCIB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XGbdzjfD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NI2Q2oPZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4tUamFjx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4Myxjjx5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xpKwmZ35_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GZhhobVH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gVIcgklg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Y00u9mh7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fShnzF6Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vMXcu3BG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k6rCCrOn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kouEbsCf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9mj57HS8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_A4VE89cJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pUlP29M1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Uec6xybF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_QTonaFRn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_7ZgxpWmI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_XCIs4h9x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_a0NX6AgL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oilnR04g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RPVSr5IQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L3PlwFKz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uewwiyoz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fehTIaCL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ez8M8jmB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_g2pWcgHy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JCfWyoDX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Usj3JcHj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gR4eKCa4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WOTwvuBu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dOF7D9bU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gkqr9BG9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hdvNVKj8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_30WAUaEv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5bYZ6A1w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tt9VCBTE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eRfzdcxr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vrp50c0I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_z6AQlV6x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9V7hCapE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_VoOQtFQq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Mpmqkd51_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CcIn2Eja_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7URQ0UUn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_20uYitHd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gogjVnb4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tnjWLZg2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1sjkqTAB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_RroKyjkR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gGeTmOtD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nIk51eYL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ntWgL4QV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xdiqb7Ub_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zBzYHOch_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_K2R7kAAV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gAazLBhB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ujAD6Q9I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_rhVihPMf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YyyaxPh2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RhoTQ84w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EBHxAA7O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_clnapMdx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_McvJelpO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_LPKXjnFR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RarwKb6E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_U9CASsdy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A6GJgRHU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cwSdw3Yw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oHjuOjbp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_n7SyTzjO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8GBmIdi0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9Ul7dTfn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Kynn60AW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qsQ4GmWj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VbCBFEdo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RiG46JpJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZAn4Ugp9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MSLowEsR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_80Jtb1iq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Dn0Hr70b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JNC3vMhX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wDOTRzCx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WjNuivSt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4U7sl5k1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5cVWvthe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_L9rYQuMU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_CQYIxZ6i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_fDtIXjPB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_t4FEP91h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nWmOfGCq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WvmecrMm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Nmk0LJfQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OOJgFhGa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TzV9MLbl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3H5xEBIZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_S36iSkEO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0KcyQMDT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_z1vBoEA1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kpel2lzl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ml7vDW4M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pFkHs7QI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZTvcqTk2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yxencfLj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bxFajgMm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mT8BPEYA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SdRzuRjs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_61xN53cU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rrK2whjm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dee55IeD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_I8Dzr7p9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5ZndH7bp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_LaANLhmR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_yGNxqQ7v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_S2cIeSM1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mJoLrax2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_icYHSeEy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VawTUqqx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qRciwK3D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5FdnEC8v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_d5eWVaV2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_JJyf1ZwV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lBavK4Yr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_UbsAhvsS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MB7oZ5bd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LdKTVRKe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iazfOgiI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NsGEkfTi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PMTReij0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lHPC7HBi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rB3X0Ovo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FgSvGsyx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ezCNSIwZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fJ9HOhnN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PjBA4mnx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kI4scJ29_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7w0f5cg6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cxI7AChy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pn63Ncj1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MACiWWpo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8XlyzY0b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DP2qh9KM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_y9BuMGNa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R9efVThn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2ghouWSh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h2hY5WMk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tZIDYP71_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oXidgDvd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YhDuXJrL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PoAOO1tc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_g8CgzAX8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_lEPZXwwr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_ZCuinEPU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BBj65Enq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qUYivrPn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mzyIhvEr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CWArySrj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QT9m1cpX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dNxDjF1h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ByPLTu9x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VrsNn9rL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cVnJyltM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HKHdvDFW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dP4ZY4jH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Kca84uFz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_e3mTYVPI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sLXKk8mb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EGR7VkBQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Gls0TVN8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zUy81bzj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Q9OJG8Bu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nl7thVYi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ePf1i2kD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oYZ1FsTQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0GGW1BfH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_LbJrDoo6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_AFzJ9h8w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JGlLEteq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D2BKVp2l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4cscjnoz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E7YlEsBS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kg2Ck6ti_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rRdNVMw8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HXOVfiuK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WWN6yWNd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_NthB2FSt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MRZOO6yP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YCUjzOVs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hDcilXtX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2cbZCCNK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FkUtYNI5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j3ZZjNbF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ACgj3xUI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tGsmIjqt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2RdC4ltE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FsQFvinu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RIZRGPuA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zJXHPS2e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZRjLDUtw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kM3GwGSd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5LqrTRRN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_asJNCnKp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NTEuAUjT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wkv9TcUD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_xYkzmJAe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Mm7luv3T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_abbMA4qQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_36UMch34_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_k2fRJtaS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L7F3vP1m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ztrm8Z4J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tKYmqA3V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bmOYzIrs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TjXjUBcH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_48SuMUGW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zYLCj9nE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Cz3GuwZ9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BH0Va8pU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_La00EYvP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lmrOE1mD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3atxc0UZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yFdjtG68_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bWgH90Yt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_j76N8V0w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HCYGsdHC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_KRne8x6H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qUvNarj0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_h0mjgQhB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_tiRp9ue3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ebO7RRGI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_m4ukc4db_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_W7TMMbMl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YLIQKlPP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_lZTumiiu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kPgmCLGF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2aqkGwsR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6FE5Ur2O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_J7yIm0MD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QfgxnE0l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F8fTk35X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SKWb7oAx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HjQdwr65_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_S2JZ2UP8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R16pcd3H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Yrgzoglk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yyTXlP7j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tuumuoxd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ii3ZVtYu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D2VjpSQb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jomJUXmJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IzZJGVQd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XgWt3e53_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_CZ74PW29_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QtFJLpTQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TcYdwwB8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_opyukWPJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_wD4HL6Uw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_onyBmimv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ec8b7Lhl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hKrFyPvG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TpyysmKi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_G8cOjACX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xBEjogG9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3yo146eR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ye9zohgj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LEG3jHU4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_anHedki1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_e5EUbfw9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LQWbGX2T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W2F1tf6l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fw5Fqe0W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8N37bZab_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_x8oWp35l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M9WNUhzg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ckQbh13f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2zQi4RLN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Gdd6m9qu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3vObl7xo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sPT8t41g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_KHQ80rZg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_8yCAl6kj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_dqQlqJgO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_TWFjXXmP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RqlvjwvO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Vfyk1Oft_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lE7wBAEf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qRFkg4Gi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Wgh4oSOl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8w0siukR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JWAbMC2U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1zF3lEX7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_d86G7Fu5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qAa5cvO0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PPoC9Ir0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zdyJU3qr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lBZcCH3N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kvgsmrkq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_k9nXxSgg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qAdS2S44_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kpB3VX0Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xzQ39nrh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_G1TkLY3Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8JlJojHw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_R4DUtnB3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7TQBqTM0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UnKx07L6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jcVtsOim_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pyyD5enJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LR7qRyJQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jK5a28cz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jI0sKwwO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_awubPIHt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yyclLtnu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_im2IeI35_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zSOSWBfv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ueY3ByoX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RFpayBpm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TQ9009B4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cMc0F9uF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_jmF2rwFD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_dRKZ5BG3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_va5RHXWr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Gt0TvWFd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lEj7sEZM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_StYlJVoX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ohdczAbR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9fs6SobJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_RSDRoNHt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_rmu1hnn2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_a5QmDK2I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4rtOBCLG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fLQneWkK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AdAfoBwz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gFi2vKF9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_a67gk6IJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_n5wAL7E1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IyAlHXJX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p4uBiqjt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MOQvxTDu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QnXCXKcy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PpHVlJi5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_I15Z20rf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KvZGPGWE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YPQbxiVY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xAgZ2bzE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_07hjlwI6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kDkw0RCD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_lEGmvfjk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_KSksH59S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_fjvu92z0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jRioezKP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_03s8fgfP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NIYDXqj2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xIVpJlvV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1KTvXhOZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_A6qphS88_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HoQpL3jr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qdcA5HGR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6Bsnhcyy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rwkhiiiK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VuTAmyqw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wCk1AQ3S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_M3WiOrko_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_kFaIg4s4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9b47s6E6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5suEOoJA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ut76ehrp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_itXrCo38_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aZC6PgV2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pfBuVoXJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_abHLbL3J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_7KclUbIu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ZnCzVpSJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Uf55ORtn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2wKygA5e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YjxtLSy7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hRlc1cBl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SPwrKFOP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_dypgIm5q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NnaUs8nj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uDyKE03O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RVuUTO7J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JDp6UCXi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9VbC1k2g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_upg3OvfG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bqwyHudi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bj1yq9DT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Iy9haA66_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PwdnFuTh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SbkGaTKJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_9bDA4EwY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_cubK1t29_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4TeKvnBE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_u5FS8vlw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FsO7FWjN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5LkZF0lE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RhxdaEgZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fTm7UCwJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WpfpMcYB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OfopRk2a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_leBbH8Se_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ScmL81if_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W6zj9iZ9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_juz5HF1J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jxMIO2sd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WTOufy7x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_f9BZsw4y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_759JmSPE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_DOpaPyJQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_7OIzZwCN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Oje0xj7y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vXN8e4Cs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IdI6YWX1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GKEVE3xV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oHQfWrzN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_g0bh6zaj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hMBFis0c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7f26ysai_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bNt6UR78_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TCh30rhx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kmyTbYum_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4ob5Fn7R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yLwMMboY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ekn87GW7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FOjFmYSA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xEsm8liV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EDaRtRIT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZNObdoZ3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jsZtCdz4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5PUaP4ak_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_05NYFyG8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hliilloW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_osuPeVaE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dHuDnzxh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GY38cGVC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_29OxxXjG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8Vx7XtOF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VueRi6VJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jY9aacAc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_32XBK37Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8cf4WXdB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5tLxLZRk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XwToN5DN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WcA0Hefp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2mNCzQ36_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2jh2JvEL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9Wo6VQF8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XxoR7ac2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SRY6HYXY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PAsf272s_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ty9xOWaL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fBjoVqSp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6goYNGlb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1lPVZina_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WkPOe91C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jKhyhJJy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_6WFEt1jK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_LRChYx4n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_QCyszybr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_oyqM5JtJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_FINoPYCW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_9IMH91wU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_YuzfBRAg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_RFVsvOge_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_AxBMWFrv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Qgl5KGCK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_n1hRzgVZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_mH83Twnq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_xXry9poh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_mqX08En5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Kat1M39k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_nTVwhylI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_IIqd3GpY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_3QNuqrQ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_C0bhJVHm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_yJSwzRvy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_p3CzG4Fj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_3C8nGPPp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_IqXJgm8e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_vYHOlTRf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_B2ngd8XP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Yg0UBiKt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_NrKxKd7X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_7SvxpBcp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_veL8rFxp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_NnwMaz6j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_oR02XZuF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Vhd0e2Fm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_c3Udbkss_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalLine sLine_9e4xL0L3;
  SignalLine sLine_nGqTF2lq;
  SignalLine sLine_OswWEXrK;
  SignalLine sLine_Tc1HbscM;
  SignalLine sLine_KpI4HxA3;
  SignalBiquad sBiquad_s_wKdo07VT;
  SignalLine sLine_ollV2Kg6;
  SignalLine sLine_h2rTC68R;
  SignalLine sLine_4LxtWRrK;
  SignalLine sLine_ULIdzvfl;
  SignalLine sLine_5uipgrk8;
  SignalBiquad sBiquad_s_rnFtbM4i;
  SignalLine sLine_EGJnCRU7;
  SignalLine sLine_c35xVqS6;
  SignalLine sLine_L6QI2sxz;
  SignalLine sLine_2aqS4R4C;
  SignalLine sLine_8CzXJsUm;
  SignalBiquad sBiquad_s_SEeodoXi;
  SignalLine sLine_wkTpzcvQ;
  SignalLine sLine_V183eFbc;
  SignalLine sLine_6nWJNpwK;
  SignalLine sLine_aujPyI3o;
  SignalLine sLine_hZX6p11G;
  SignalBiquad sBiquad_s_5xrS1eni;
  SignalLine sLine_zV1pENor;
  SignalLine sLine_dEacS5S5;
  SignalLine sLine_ig1MqdXn;
  SignalLine sLine_5sbSW92o;
  SignalLine sLine_0ufmkMY6;
  SignalBiquad sBiquad_s_cbMwCZen;
  SignalLine sLine_853HbX5T;
  SignalLine sLine_tfawjeIt;
  SignalLine sLine_mSP6osrT;
  SignalLine sLine_UNC9iX7K;
  SignalLine sLine_7fHdDRHo;
  SignalBiquad sBiquad_s_P0cKR8Qx;
  SignalLine sLine_CFcusdIv;
  SignalLine sLine_ycUzQxqt;
  SignalLine sLine_d2zk7NHW;
  SignalLine sLine_hWxlgDVl;
  SignalLine sLine_VCxDIKgm;
  SignalBiquad sBiquad_s_2uDpJATX;
  ControlVar cVar_IFqHHym8;
  ControlVar cVar_ZqSXEZAv;
  ControlBinop cBinop_TAbWBTBr;
  ControlBinop cBinop_WW4KDjK2;
  ControlBinop cBinop_sue5sZ8Q;
  ControlBinop cBinop_34bo36jI;
  ControlBinop cBinop_0RmdBP81;
  ControlBinop cBinop_rrz9kOvO;
  ControlVar cVar_ACtj0btH;
  ControlBinop cBinop_vUja36ow;
  ControlBinop cBinop_kWSKR1HY;
  ControlBinop cBinop_xbU2Syu3;
  ControlVar cVar_1mWQw5eI;
  ControlBinop cBinop_Eoz0PwbO;
  ControlBinop cBinop_ebGIIkw4;
  ControlBinop cBinop_JsYKaaJb;
  ControlBinop cBinop_1iggz5hh;
  ControlBinop cBinop_cegagA1a;
  ControlBinop cBinop_pFAZIk2o;
  ControlBinop cBinop_B4ZO7Tbg;
  ControlBinop cBinop_4dWyDkbH;
  ControlBinop cBinop_oBBW4syz;
  ControlBinop cBinop_k4udKMhm;
  ControlBinop cBinop_rCVE6Mzx;
  ControlBinop cBinop_glj3pwTo;
  ControlBinop cBinop_R2TVZSKV;
  ControlBinop cBinop_cW5Lsfh9;
  ControlBinop cBinop_jLuFgeqI;
  ControlBinop cBinop_VeSQbFES;
  ControlBinop cBinop_YE8MpmLJ;
  ControlBinop cBinop_CFDGpu1y;
  ControlBinop cBinop_Xg39tw28;
  ControlBinop cBinop_AKNTLWx0;
  ControlBinop cBinop_0MODuUKy;
  ControlBinop cBinop_6aQfvPOz;
  ControlBinop cBinop_F9UbFMyW;
  ControlBinop cBinop_x5SIAMJh;
  ControlBinop cBinop_6sFgKLWy;
  ControlBinop cBinop_rP6ZRrw8;
  ControlBinop cBinop_OdmWq08A;
  ControlBinop cBinop_nNPauLjB;
  ControlBinop cBinop_RvXiE4wD;
  ControlBinop cBinop_g6UKIeBD;
  ControlVar cVar_EctSGFui;
  ControlVar cVar_7H9YyhX8;
  ControlBinop cBinop_FkiukWLl;
  ControlBinop cBinop_8D2MSav8;
  ControlBinop cBinop_xatg3L5l;
  ControlBinop cBinop_gi2tqjb9;
  ControlBinop cBinop_hw50gjbw;
  ControlBinop cBinop_Q2j1jaeZ;
  ControlBinop cBinop_3qxZhCIB;
  ControlBinop cBinop_XGbdzjfD;
  ControlBinop cBinop_NI2Q2oPZ;
  ControlBinop cBinop_4tUamFjx;
  ControlBinop cBinop_4Myxjjx5;
  ControlBinop cBinop_xpKwmZ35;
  ControlBinop cBinop_GZhhobVH;
  ControlBinop cBinop_gVIcgklg;
  ControlBinop cBinop_Y00u9mh7;
  ControlBinop cBinop_fShnzF6Z;
  ControlBinop cBinop_vMXcu3BG;
  ControlBinop cBinop_k6rCCrOn;
  ControlBinop cBinop_pUlP29M1;
  ControlVar cVar_VoOQtFQq;
  ControlBinop cBinop_tnjWLZg2;
  ControlBinop cBinop_1sjkqTAB;
  ControlVar cVar_RroKyjkR;
  ControlBinop cBinop_gGeTmOtD;
  ControlBinop cBinop_nIk51eYL;
  ControlVar cVar_ntWgL4QV;
  ControlBinop cBinop_xdiqb7Ub;
  ControlBinop cBinop_zBzYHOch;
  ControlBinop cBinop_gAazLBhB;
  ControlVar cVar_YyyaxPh2;
  ControlBinop cBinop_RhoTQ84w;
  ControlBinop cBinop_RarwKb6E;
  ControlBinop cBinop_U9CASsdy;
  ControlBinop cBinop_A6GJgRHU;
  ControlBinop cBinop_n7SyTzjO;
  ControlBinop cBinop_8GBmIdi0;
  ControlBinop cBinop_Kynn60AW;
  ControlBinop cBinop_qsQ4GmWj;
  ControlBinop cBinop_RiG46JpJ;
  ControlBinop cBinop_ZAn4Ugp9;
  ControlBinop cBinop_MSLowEsR;
  ControlBinop cBinop_80Jtb1iq;
  ControlBinop cBinop_Dn0Hr70b;
  ControlBinop cBinop_JNC3vMhX;
  ControlBinop cBinop_wDOTRzCx;
  ControlBinop cBinop_WjNuivSt;
  ControlBinop cBinop_4U7sl5k1;
  ControlVar cVar_ZTvcqTk2;
  ControlVar cVar_yxencfLj;
  ControlVar cVar_bxFajgMm;
  ControlVar cVar_I8Dzr7p9;
  ControlVar cVar_5ZndH7bp;
  ControlBinop cBinop_S2cIeSM1;
  ControlBinop cBinop_mJoLrax2;
  ControlBinop cBinop_VawTUqqx;
  ControlVar cVar_qRciwK3D;
  ControlBinop cBinop_5FdnEC8v;
  ControlBinop cBinop_MB7oZ5bd;
  ControlBinop cBinop_LdKTVRKe;
  ControlBinop cBinop_iazfOgiI;
  ControlBinop cBinop_lHPC7HBi;
  ControlBinop cBinop_rB3X0Ovo;
  ControlBinop cBinop_FgSvGsyx;
  ControlBinop cBinop_ezCNSIwZ;
  ControlBinop cBinop_PjBA4mnx;
  ControlBinop cBinop_kI4scJ29;
  ControlBinop cBinop_7w0f5cg6;
  ControlBinop cBinop_cxI7AChy;
  ControlBinop cBinop_MACiWWpo;
  ControlBinop cBinop_8XlyzY0b;
  ControlBinop cBinop_DP2qh9KM;
  ControlBinop cBinop_y9BuMGNa;
  ControlBinop cBinop_R9efVThn;
  ControlBinop cBinop_2ghouWSh;
  ControlBinop cBinop_h2hY5WMk;
  ControlBinop cBinop_tZIDYP71;
  ControlBinop cBinop_oXidgDvd;
  ControlBinop cBinop_sLXKk8mb;
  ControlBinop cBinop_EGR7VkBQ;
  ControlBinop cBinop_Gls0TVN8;
  ControlBinop cBinop_zUy81bzj;
  ControlBinop cBinop_nl7thVYi;
  ControlVar cVar_oYZ1FsTQ;
  ControlBinop cBinop_JGlLEteq;
  ControlBinop cBinop_D2BKVp2l;
  ControlBinop cBinop_4cscjnoz;
  ControlVar cVar_rRdNVMw8;
  ControlBinop cBinop_HXOVfiuK;
  ControlBinop cBinop_WWN6yWNd;
  ControlBinop cBinop_MRZOO6yP;
  ControlBinop cBinop_YCUjzOVs;
  ControlBinop cBinop_hDcilXtX;
  ControlVar cVar_2cbZCCNK;
  ControlBinop cBinop_FkUtYNI5;
  ControlBinop cBinop_j3ZZjNbF;
  ControlBinop cBinop_ACgj3xUI;
  ControlBinop cBinop_tGsmIjqt;
  ControlBinop cBinop_2RdC4ltE;
  ControlBinop cBinop_FsQFvinu;
  ControlBinop cBinop_RIZRGPuA;
  ControlBinop cBinop_zJXHPS2e;
  ControlBinop cBinop_ZRjLDUtw;
  ControlBinop cBinop_kM3GwGSd;
  ControlBinop cBinop_5LqrTRRN;
  ControlBinop cBinop_asJNCnKp;
  ControlVar cVar_j76N8V0w;
  ControlVar cVar_HCYGsdHC;
  ControlVar cVar_KRne8x6H;
  ControlVar cVar_qUvNarj0;
  ControlVar cVar_h0mjgQhB;
  ControlVar cVar_tiRp9ue3;
  SignalVarf sVarf_CEpoV4ys;
  ControlVar cVar_ebO7RRGI;
  ControlBinop cBinop_kPgmCLGF;
  ControlBinop cBinop_2aqkGwsR;
  ControlVar cVar_J7yIm0MD;
  ControlBinop cBinop_QfgxnE0l;
  ControlBinop cBinop_F8fTk35X;
  ControlBinop cBinop_SKWb7oAx;
  ControlBinop cBinop_HjQdwr65;
  ControlBinop cBinop_S2JZ2UP8;
  ControlBinop cBinop_R16pcd3H;
  ControlVar cVar_Yrgzoglk;
  ControlBinop cBinop_yyTXlP7j;
  ControlBinop cBinop_tuumuoxd;
  ControlBinop cBinop_Ii3ZVtYu;
  ControlBinop cBinop_D2VjpSQb;
  ControlBinop cBinop_jomJUXmJ;
  ControlBinop cBinop_IzZJGVQd;
  ControlVar cVar_CZ74PW29;
  ControlBinop cBinop_QtFJLpTQ;
  ControlBinop cBinop_TcYdwwB8;
  ControlBinop cBinop_ec8b7Lhl;
  ControlBinop cBinop_hKrFyPvG;
  ControlBinop cBinop_TpyysmKi;
  ControlVar cVar_3yo146eR;
  ControlBinop cBinop_LEG3jHU4;
  ControlBinop cBinop_anHedki1;
  ControlBinop cBinop_e5EUbfw9;
  ControlBinop cBinop_LQWbGX2T;
  ControlBinop cBinop_W2F1tf6l;
  ControlBinop cBinop_fw5Fqe0W;
  ControlBinop cBinop_8N37bZab;
  ControlBinop cBinop_x8oWp35l;
  ControlBinop cBinop_M9WNUhzg;
  ControlBinop cBinop_ckQbh13f;
  ControlBinop cBinop_sPT8t41g;
  ControlBinop cBinop_pyyD5enJ;
  ControlBinop cBinop_LR7qRyJQ;
  ControlBinop cBinop_jK5a28cz;
  ControlBinop cBinop_awubPIHt;
  ControlBinop cBinop_yyclLtnu;
  ControlBinop cBinop_im2IeI35;
  ControlBinop cBinop_ueY3ByoX;
  ControlBinop cBinop_RFpayBpm;
  ControlBinop cBinop_cMc0F9uF;
  ControlVar cVar_dRKZ5BG3;
  ControlBinop cBinop_va5RHXWr;
  ControlBinop cBinop_Gt0TvWFd;
  ControlBinop cBinop_lEj7sEZM;
  ControlBinop cBinop_a5QmDK2I;
  ControlBinop cBinop_4rtOBCLG;
  ControlBinop cBinop_fLQneWkK;
  ControlVar cVar_a67gk6IJ;
  ControlVar cVar_n5wAL7E1;
  ControlBinop cBinop_IyAlHXJX;
  ControlBinop cBinop_p4uBiqjt;
  ControlBinop cBinop_MOQvxTDu;
  ControlBinop cBinop_QnXCXKcy;
  ControlBinop cBinop_PpHVlJi5;
  ControlBinop cBinop_I15Z20rf;
  ControlBinop cBinop_KvZGPGWE;
  ControlBinop cBinop_YPQbxiVY;
  ControlBinop cBinop_xAgZ2bzE;
  ControlVar cVar_kFaIg4s4;
  ControlBinop cBinop_aZC6PgV2;
  ControlBinop cBinop_Uf55ORtn;
  ControlBinop cBinop_2wKygA5e;
  ControlBinop cBinop_YjxtLSy7;
  ControlVar cVar_dypgIm5q;
  ControlBinop cBinop_NnaUs8nj;
  ControlBinop cBinop_RVuUTO7J;
  ControlBinop cBinop_JDp6UCXi;
  ControlBinop cBinop_9VbC1k2g;
  ControlBinop cBinop_upg3OvfG;
  ControlBinop cBinop_bj1yq9DT;
  ControlBinop cBinop_Iy9haA66;
  ControlBinop cBinop_PwdnFuTh;
  ControlVar cVar_SbkGaTKJ;
  ControlBinop cBinop_4TeKvnBE;
  ControlVar cVar_u5FS8vlw;
  ControlBinop cBinop_FsO7FWjN;
  ControlBinop cBinop_5LkZF0lE;
  ControlBinop cBinop_fTm7UCwJ;
  ControlBinop cBinop_WpfpMcYB;
  ControlBinop cBinop_OfopRk2a;
  ControlBinop cBinop_leBbH8Se;
  ControlBinop cBinop_ScmL81if;
  ControlBinop cBinop_W6zj9iZ9;
  ControlBinop cBinop_juz5HF1J;
  ControlBinop cBinop_jxMIO2sd;
  ControlBinop cBinop_WTOufy7x;
  ControlVar cVar_FOjFmYSA;
  SignalVarf sVarf_xerhqfUe;
  SignalVarf sVarf_TN6iClnE;
  ControlBinop cBinop_EDaRtRIT;
  ControlBinop cBinop_ZNObdoZ3;
  ControlBinop cBinop_jsZtCdz4;
  ControlBinop cBinop_5PUaP4ak;
  ControlBinop cBinop_05NYFyG8;
  ControlBinop cBinop_hliilloW;
  ControlBinop cBinop_osuPeVaE;
  ControlBinop cBinop_dHuDnzxh;
  ControlBinop cBinop_GY38cGVC;
  ControlBinop cBinop_29OxxXjG;
  ControlBinop cBinop_8Vx7XtOF;
  ControlBinop cBinop_VueRi6VJ;
  ControlBinop cBinop_jY9aacAc;
  ControlBinop cBinop_32XBK37Z;
  ControlBinop cBinop_8cf4WXdB;
  ControlBinop cBinop_5tLxLZRk;
  ControlBinop cBinop_XwToN5DN;
  ControlBinop cBinop_WcA0Hefp;
  SignalVarf sVarf_4fREovV8;
  SignalVarf sVarf_OKELXIQ2;
  SignalVarf sVarf_sqtSypp4;
  SignalVarf sVarf_jEvqjtKG;
  SignalVarf sVarf_W5h4cIYu;
  SignalVarf sVarf_9YgrJmHN;
};

#endif // _HEAVY_CONTEXT_POLYCULE_HPP_
